        !COMPILER-GENERATED INTERFACE MODULE: Sat Feb 18 13:28:29 2017
        MODULE ANGLES_RAZRYV__genmod
          INTERFACE 
            SUBROUTINE ANGLES_RAZRYV(NJ1,ALPHA)
              INTEGER(KIND=4) :: NJ1
              REAL(KIND=8) :: ALPHA(NJ1)
            END SUBROUTINE ANGLES_RAZRYV
          END INTERFACE 
        END MODULE ANGLES_RAZRYV__genmod
