        !COMPILER-GENERATED INTERFACE MODULE: Sat Feb 18 13:28:27 2017
        MODULE FIND_CONST__genmod
          INTERFACE 
            SUBROUTINE FIND_CONST
            END SUBROUTINE FIND_CONST
          END INTERFACE 
        END MODULE FIND_CONST__genmod
