        !COMPILER-GENERATED INTERFACE MODULE: Sat Feb 18 13:28:28 2017
        MODULE FORMA_PLASTINKI__genmod
          INTERFACE 
            SUBROUTINE FORMA_PLASTINKI
            END SUBROUTINE FORMA_PLASTINKI
          END INTERFACE 
        END MODULE FORMA_PLASTINKI__genmod
