        !COMPILER-GENERATED INTERFACE MODULE: Fri Feb 26 09:53:09 2016
        MODULE SOLVE_EQUETION__genmod
          INTERFACE 
            SUBROUTINE SOLVE_EQUETION(X0,Y0)
              REAL(KIND=8) :: X0
              REAL(KIND=8) :: Y0
            END SUBROUTINE SOLVE_EQUETION
          END INTERFACE 
        END MODULE SOLVE_EQUETION__genmod
